package com.linkplatform.api.owner.application;

public enum SecurityEventType {
    API_KEY_CREATED,
    API_KEY_REVOKED,
    API_KEY_ROTATED,
    API_KEY_EXPIRED,
    MISSING_CREDENTIAL,
    MALFORMED_BEARER,
    AMBIGUOUS_CREDENTIAL,
    INVALID_CREDENTIAL,
    RATE_LIMIT_REJECTED,
    QUOTA_REJECTED,
    CLICK_ROLLUP_DRIFT_DETECTED,
    CLICK_ROLLUP_REPAIRED,
    QUERY_DATASOURCE_FALLBACK,
    RUNTIME_CONFIGURATION_REJECTED,
    REDIRECT_LOOKUP_FAILED,
    REDIRECT_FAILOVER_ACTIVATED,
    REDIRECT_UNAVAILABLE
}
