package com.linkplatform.api.owner.application;

public enum SecurityEventType {
    MISSING_CREDENTIAL,
    MALFORMED_BEARER_TOKEN,
    AMBIGUOUS_CREDENTIAL,
    INVALID_CREDENTIAL,
    RATE_LIMIT_REJECTED,
    QUOTA_REJECTED,
    QUERY_DATASOURCE_FALLBACK,
    RUNTIME_CONFIGURATION_REJECTED,
    REDIRECT_LOOKUP_FAILED,
    REDIRECT_FAILOVER_ACTIVATED,
    REDIRECT_UNAVAILABLE
}
