package com.linkplatform.api.projection;

import java.time.OffsetDateTime;

public record ProjectionJob(
        long id,
        ProjectionJobType jobType,
        ProjectionJobStatus status,
        OffsetDateTime requestedAt,
        OffsetDateTime startedAt,
        OffsetDateTime lastChunkAt,
        OffsetDateTime completedAt,
        long processedCount,
        long processedItems,
        long failedItems,
        Long checkpointId,
        String errorSummary,
        String lastError,
        String claimedBy,
        OffsetDateTime claimedUntil,
        Long ownerId,
        Long workspaceId,
        String slug,
        OffsetDateTime rangeStart,
        OffsetDateTime rangeEnd,
        Long requestedByOwnerId,
        String operatorNote) {

    public ProjectionJob(
            long id,
            ProjectionJobType jobType,
            ProjectionJobStatus status,
            OffsetDateTime requestedAt,
            OffsetDateTime startedAt,
            OffsetDateTime lastChunkAt,
            OffsetDateTime completedAt,
            long processedCount,
            long processedItems,
            long failedItems,
            Long checkpointId,
            String errorSummary,
            String lastError,
            String claimedBy,
            OffsetDateTime claimedUntil) {
        this(
                id,
                jobType,
                status,
                requestedAt,
                startedAt,
                lastChunkAt,
                completedAt,
                processedCount,
                processedItems,
                failedItems,
                checkpointId,
                errorSummary,
                lastError,
                claimedBy,
                claimedUntil,
                null,
                null,
                null,
                null,
                null,
                null,
                null);
    }

    public ProjectionJob(
            long id,
            ProjectionJobType jobType,
            ProjectionJobStatus status,
            OffsetDateTime requestedAt,
            OffsetDateTime startedAt,
            OffsetDateTime completedAt,
            long processedCount,
            Long checkpointId,
            String errorSummary,
            String claimedBy,
            OffsetDateTime claimedUntil,
            Long ownerId,
            String slug) {
        this(
                id,
                jobType,
                status,
                requestedAt,
                startedAt,
                null,
                completedAt,
                processedCount,
                processedCount,
                0L,
                checkpointId,
                errorSummary,
                errorSummary,
                claimedBy,
                claimedUntil,
                ownerId,
                null,
                slug,
                null,
                null,
                null,
                null);
    }

    public ProjectionJob(
            long id,
            ProjectionJobType jobType,
            ProjectionJobStatus status,
            OffsetDateTime requestedAt,
            OffsetDateTime startedAt,
            OffsetDateTime completedAt,
            long processedCount,
            Long checkpointId,
            String errorSummary,
            String lastError,
            OffsetDateTime claimedUntil,
            Long ownerId,
            Long workspaceId,
            String slug,
            OffsetDateTime rangeStart,
            OffsetDateTime rangeEnd,
            Long requestedByOwnerId,
            String operatorNote) {
        this(
                id,
                jobType,
                status,
                requestedAt,
                startedAt,
                null,
                completedAt,
                processedCount,
                processedCount,
                0L,
                checkpointId,
                errorSummary,
                lastError,
                null,
                claimedUntil,
                ownerId,
                workspaceId,
                slug,
                rangeStart,
                rangeEnd,
                requestedByOwnerId,
                operatorNote);
    }

    public ProjectionJob(
            long id,
            ProjectionJobType jobType,
            ProjectionJobStatus status,
            OffsetDateTime requestedAt,
            OffsetDateTime startedAt,
            OffsetDateTime completedAt,
            long processedCount,
            Long checkpointId,
            String errorSummary,
            String claimedBy,
            OffsetDateTime claimedUntil) {
        this(id, jobType, status, requestedAt, startedAt, completedAt, processedCount, checkpointId, errorSummary, claimedBy, claimedUntil, null, null);
    }
}
