CREATE TABLE link_lifecycle_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(100) NOT NULL UNIQUE,
    event_type VARCHAR(50) NOT NULL,
    event_key VARCHAR(255) NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMP WITH TIME ZONE,
    claimed_by VARCHAR(100),
    claimed_until TIMESTAMP WITH TIME ZONE,
    attempt_count INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP WITH TIME ZONE,
    last_error_summary VARCHAR(255),
    parked_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_link_lifecycle_outbox_delivery
    ON link_lifecycle_outbox (published_at, parked_at, next_attempt_at, claimed_until, created_at, id);
