CREATE TABLE projection_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_type VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    processed_count BIGINT NOT NULL DEFAULT 0,
    error_summary VARCHAR(255),
    claimed_by VARCHAR(100),
    claimed_until TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_projection_jobs_claimable
    ON projection_jobs (status, claimed_until, requested_at, id);
