CREATE TABLE owners (
    id BIGINT PRIMARY KEY,
    owner_key VARCHAR(100) NOT NULL UNIQUE,
    display_name VARCHAR(255) NOT NULL,
    plan VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE owner_api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES owners (id),
    key_hash CHAR(64) NOT NULL UNIQUE,
    key_label VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO owners (id, owner_key, display_name, plan)
VALUES
    (1, 'free-owner', 'Free Owner', 'FREE'),
    (2, 'pro-owner', 'Pro Owner', 'PRO');

INSERT INTO owner_api_keys (owner_id, key_hash, key_label)
VALUES
    (1, '5cd81fa8d1b30a1619001c1fd727555a9a17cc23d551587bb214dccbd1f59606', 'free-owner-default'),
    (2, 'cf902ffdf26b6dc7450ee9d173b5766fbadcafbc19a8c7b1d320c831ecb886e7', 'pro-owner-default');

ALTER TABLE links
    ADD COLUMN owner_id BIGINT NOT NULL DEFAULT 1 REFERENCES owners (id);

CREATE INDEX idx_links_owner_id ON links (owner_id);

ALTER TABLE link_catalog_projection
    ADD COLUMN owner_id BIGINT NOT NULL DEFAULT 1 REFERENCES owners (id);

CREATE INDEX idx_link_catalog_projection_owner_id_created_at
    ON link_catalog_projection (owner_id, created_at DESC, slug ASC);

CREATE TABLE link_mutation_idempotency_v2 (
    owner_id BIGINT NOT NULL REFERENCES owners (id),
    idempotency_key VARCHAR(200) NOT NULL,
    operation VARCHAR(32) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    response_json TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (owner_id, idempotency_key)
);

INSERT INTO link_mutation_idempotency_v2 (owner_id, idempotency_key, operation, request_hash, response_json, created_at)
SELECT 1, idempotency_key, operation, request_hash, response_json, created_at
FROM link_mutation_idempotency;

DROP TABLE link_mutation_idempotency;

ALTER TABLE link_mutation_idempotency_v2 RENAME TO link_mutation_idempotency;
