CREATE TABLE owners (
    id BIGINT PRIMARY KEY,
    owner_key VARCHAR(100) NOT NULL UNIQUE,
    display_name VARCHAR(255) NOT NULL,
    plan VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE owner_api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    key_hash CHAR(64) NOT NULL UNIQUE,
    key_label VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_owner_api_keys_owner
        FOREIGN KEY (owner_id) REFERENCES owners (id)
);

INSERT INTO owners (id, owner_key, display_name, plan)
VALUES
    (100, 'free-dev-owner', 'Free Dev Owner', 'FREE'),
    (200, 'pro-dev-owner', 'Pro Dev Owner', 'PRO');

INSERT INTO owner_api_keys (owner_id, key_hash, key_label)
VALUES
    (100, 'f5bb22ef299395119b03da89f2037fcdd69d0257d27e1aa0cba2f1729a0dc59e', 'dev-free-key'),
    (200, 'fb869a22677fb2960fd1412adad7e78658762067ae2fb1acfa5faccbbe78f199', 'dev-pro-key');
