CREATE TABLE owner_control_plane_rate_limits (
    owner_id BIGINT NOT NULL REFERENCES owners (id),
    rate_limit_bucket VARCHAR(32) NOT NULL,
    window_started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    request_count INT NOT NULL,
    PRIMARY KEY (owner_id, rate_limit_bucket, window_started_at)
);

CREATE TABLE owner_security_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(50) NOT NULL,
    owner_id BIGINT REFERENCES owners (id),
    api_key_hash CHAR(64),
    request_method VARCHAR(16),
    request_path VARCHAR(255),
    remote_address VARCHAR(255),
    detail_summary VARCHAR(255) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_owner_security_events_occurred_at
    ON owner_security_events (occurred_at DESC, id DESC);
