CREATE TABLE click_rollup_reconciliation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES owners (id),
    slug VARCHAR(255) NOT NULL REFERENCES links (slug),
    bucket_day DATE NOT NULL,
    raw_click_count BIGINT NOT NULL,
    rollup_click_count BIGINT NOT NULL,
    drift_count BIGINT NOT NULL,
    detected_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    repaired_at TIMESTAMP WITH TIME ZONE,
    repair_status VARCHAR(32) NOT NULL,
    repair_note VARCHAR(255),
    CONSTRAINT uk_click_rollup_reconciliation_owner_slug_day UNIQUE (owner_id, slug, bucket_day)
);

CREATE INDEX idx_click_rollup_reconciliation_detected_at
    ON click_rollup_reconciliation (detected_at DESC, id DESC);
