CREATE TABLE workspaces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(120) NOT NULL UNIQUE,
    display_name VARCHAR(160) NOT NULL,
    personal_workspace BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by_owner_id BIGINT NOT NULL REFERENCES owners (id),
    archived_at TIMESTAMP WITH TIME ZONE
);

CREATE UNIQUE INDEX uk_workspaces_slug
    ON workspaces (slug);

CREATE TABLE workspace_members (
    workspace_id BIGINT NOT NULL REFERENCES workspaces (id),
    owner_id BIGINT NOT NULL REFERENCES owners (id),
    role VARCHAR(32) NOT NULL,
    joined_at TIMESTAMP WITH TIME ZONE NOT NULL,
    added_by_owner_id BIGINT REFERENCES owners (id),
    removed_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (workspace_id, owner_id)
);

CREATE INDEX idx_workspace_members_owner_id
    ON workspace_members (owner_id);

CREATE INDEX idx_workspace_members_workspace_removed
    ON workspace_members (workspace_id, removed_at);
