CREATE TABLE link_abuse_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    slug VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    source VARCHAR(32) NOT NULL,
    signal_count BIGINT NOT NULL DEFAULT 1,
    risk_score INTEGER NOT NULL,
    summary VARCHAR(255) NOT NULL,
    detail_summary VARCHAR(1024),
    target_host VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by_owner_id BIGINT,
    reviewed_at TIMESTAMP WITH TIME ZONE,
    reviewed_by_owner_id BIGINT,
    resolution VARCHAR(32),
    resolution_note VARCHAR(512)
);

CREATE INDEX idx_link_abuse_cases_workspace_status_updated
    ON link_abuse_cases (workspace_id, status, updated_at DESC);

CREATE INDEX idx_link_abuse_cases_workspace_slug
    ON link_abuse_cases (workspace_id, slug);

CREATE INDEX idx_link_abuse_cases_workspace_source_status
    ON link_abuse_cases (workspace_id, source, status);
