CREATE TABLE operator_action_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT REFERENCES workspaces (id),
    owner_id BIGINT NOT NULL REFERENCES owners (id),
    subsystem VARCHAR(32) NOT NULL,
    action_type VARCHAR(64) NOT NULL,
    target_slug VARCHAR(255),
    target_case_id BIGINT,
    target_projection_job_id BIGINT,
    note VARCHAR(512),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_operator_action_log_workspace_created
    ON operator_action_log (workspace_id, created_at DESC);

CREATE INDEX idx_operator_action_log_subsystem_created
    ON operator_action_log (subsystem, created_at DESC);

CREATE INDEX idx_operator_action_log_projection_job
    ON operator_action_log (target_projection_job_id);

CREATE INDEX idx_operator_action_log_case
    ON operator_action_log (target_case_id);
