CREATE TABLE workspace_plans (
    workspace_id BIGINT PRIMARY KEY,
    plan_code VARCHAR(32) NOT NULL,
    active_links_limit INTEGER NOT NULL,
    members_limit INTEGER NOT NULL,
    api_keys_limit INTEGER NOT NULL,
    webhooks_limit INTEGER NOT NULL,
    monthly_webhook_deliveries_limit BIGINT NOT NULL,
    exports_enabled BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE workspace_usage_ledger (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    workspace_id BIGINT NOT NULL,
    metric_code VARCHAR(64) NOT NULL,
    quantity BIGINT NOT NULL,
    window_start TIMESTAMPTZ NULL,
    window_end TIMESTAMPTZ NULL,
    source VARCHAR(64) NOT NULL,
    source_ref VARCHAR(255) NULL,
    recorded_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_workspace_usage_ledger_workspace_metric_recorded
    ON workspace_usage_ledger (workspace_id, metric_code, recorded_at DESC);
CREATE INDEX idx_workspace_usage_ledger_workspace_metric_window
    ON workspace_usage_ledger (workspace_id, metric_code, window_start, window_end);

INSERT INTO workspace_plans (
    workspace_id,
    plan_code,
    active_links_limit,
    members_limit,
    api_keys_limit,
    webhooks_limit,
    monthly_webhook_deliveries_limit,
    exports_enabled,
    created_at,
    updated_at
)
SELECT
    w.id,
    'FREE',
    100,
    5,
    10,
    5,
    10000,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM workspaces w
LEFT JOIN workspace_plans p ON p.workspace_id = w.id
WHERE p.workspace_id IS NULL;
