CREATE TABLE webhook_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    callback_url VARCHAR(1024) NOT NULL,
    signing_secret_hash VARCHAR(255) NOT NULL,
    signing_secret_prefix VARCHAR(32) NOT NULL,
    enabled BOOLEAN NOT NULL,
    event_types_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    last_delivery_at TIMESTAMPTZ NULL,
    last_failure_at TIMESTAMPTZ NULL,
    consecutive_failures INTEGER NOT NULL DEFAULT 0,
    disabled_at TIMESTAMPTZ NULL,
    disabled_reason VARCHAR(255) NULL
);

CREATE TABLE webhook_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT NOT NULL,
    workspace_id BIGINT NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    event_id VARCHAR(128) NOT NULL,
    payload_json JSONB NOT NULL,
    status VARCHAR(32) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NULL,
    delivered_at TIMESTAMPTZ NULL,
    last_error VARCHAR(1024) NULL,
    http_status INTEGER NULL,
    response_excerpt VARCHAR(1024) NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    parked_at TIMESTAMPTZ NULL
);

CREATE INDEX idx_webhook_subscriptions_workspace_created
    ON webhook_subscriptions (workspace_id, created_at DESC);
CREATE INDEX idx_webhook_deliveries_workspace_created
    ON webhook_deliveries (workspace_id, created_at DESC);
CREATE INDEX idx_webhook_deliveries_subscription_created
    ON webhook_deliveries (subscription_id, created_at DESC);
CREATE INDEX idx_webhook_deliveries_status_next_attempt
    ON webhook_deliveries (status, next_attempt_at);
CREATE UNIQUE INDEX uq_webhook_deliveries_subscription_event
    ON webhook_deliveries (subscription_id, event_id);
