CREATE TABLE workspace_exports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    requested_by_owner_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    include_clicks BOOLEAN NOT NULL,
    include_security_events BOOLEAN NOT NULL,
    include_abuse_cases BOOLEAN NOT NULL,
    include_webhooks BOOLEAN NOT NULL,
    payload_json JSONB NULL,
    payload_size_bytes BIGINT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    started_at TIMESTAMPTZ NULL,
    completed_at TIMESTAMPTZ NULL,
    failed_at TIMESTAMPTZ NULL,
    last_error VARCHAR(1024) NULL
);

CREATE TABLE workspace_retention_policies (
    workspace_id BIGINT PRIMARY KEY,
    click_history_days INTEGER NOT NULL,
    security_events_days INTEGER NOT NULL,
    webhook_deliveries_days INTEGER NOT NULL,
    abuse_cases_days INTEGER NOT NULL,
    operator_action_log_days INTEGER NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    updated_by_owner_id BIGINT NOT NULL
);

CREATE INDEX idx_workspace_exports_workspace_created
    ON workspace_exports (workspace_id, created_at DESC);

INSERT INTO workspace_retention_policies (
    workspace_id,
    click_history_days,
    security_events_days,
    webhook_deliveries_days,
    abuse_cases_days,
    operator_action_log_days,
    updated_at,
    updated_by_owner_id
)
SELECT
    w.id,
    365,
    365,
    90,
    365,
    365,
    CURRENT_TIMESTAMP,
    w.created_by_owner_id
FROM workspaces w
LEFT JOIN workspace_retention_policies p ON p.workspace_id = w.id
WHERE p.workspace_id IS NULL;
