CREATE TABLE workspace_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    email VARCHAR(255) NOT NULL,
    role VARCHAR(32) NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    token_prefix VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    created_by_owner_id BIGINT NOT NULL,
    accepted_at TIMESTAMPTZ NULL,
    accepted_by_owner_id BIGINT NULL,
    revoked_at TIMESTAMPTZ NULL,
    revoked_by_owner_id BIGINT NULL
);

CREATE INDEX idx_workspace_invitations_workspace_status_created
    ON workspace_invitations (workspace_id, status, created_at DESC);
CREATE UNIQUE INDEX uq_workspace_invitations_pending_email
    ON workspace_invitations (workspace_id, lower(email), status)
    WHERE status = 'PENDING';

CREATE TABLE service_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(120) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    created_by_owner_id BIGINT NOT NULL,
    disabled_at TIMESTAMPTZ NULL,
    disabled_by_owner_id BIGINT NULL
);

CREATE UNIQUE INDEX uq_service_accounts_workspace_slug
    ON service_accounts (workspace_id, slug);
CREATE INDEX idx_service_accounts_workspace_status
    ON service_accounts (workspace_id, status);

ALTER TABLE workspace_members
    ADD COLUMN member_type VARCHAR(32) NOT NULL DEFAULT 'HUMAN',
    ADD COLUMN suspended_at TIMESTAMPTZ NULL,
    ADD COLUMN suspended_by_owner_id BIGINT NULL,
    ADD COLUMN suspend_reason VARCHAR(255) NULL;

ALTER TABLE workspaces
    ADD COLUMN status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN suspended_at TIMESTAMPTZ NULL,
    ADD COLUMN suspended_by_owner_id BIGINT NULL,
    ADD COLUMN suspend_reason VARCHAR(255) NULL;
