CREATE TABLE workspace_import_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    requested_by_owner_id BIGINT NOT NULL,
    source_export_id BIGINT NULL,
    status VARCHAR(32) NOT NULL,
    dry_run BOOLEAN NOT NULL,
    overwrite_conflicts BOOLEAN NOT NULL,
    payload_json JSONB NOT NULL,
    summary_json JSONB NULL,
    created_at TIMESTAMPTZ NOT NULL,
    started_at TIMESTAMPTZ NULL,
    completed_at TIMESTAMPTZ NULL,
    failed_at TIMESTAMPTZ NULL,
    last_error VARCHAR(1024) NULL
);

CREATE INDEX idx_workspace_import_jobs_workspace_created
    ON workspace_import_jobs (workspace_id, created_at DESC);
