CREATE TABLE workspace_abuse_policies (
    workspace_id BIGINT PRIMARY KEY,
    raw_ip_review_enabled BOOLEAN NOT NULL,
    punycode_review_enabled BOOLEAN NOT NULL,
    repeated_host_quarantine_threshold INTEGER NOT NULL,
    redirect_rate_limit_quarantine_threshold INTEGER NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    updated_by_owner_id BIGINT NOT NULL
);

INSERT INTO workspace_abuse_policies (
    workspace_id,
    raw_ip_review_enabled,
    punycode_review_enabled,
    repeated_host_quarantine_threshold,
    redirect_rate_limit_quarantine_threshold,
    updated_at,
    updated_by_owner_id
)
SELECT
    w.id,
    TRUE,
    TRUE,
    3,
    5,
    CURRENT_TIMESTAMP,
    w.created_by_owner_id
FROM workspaces w
LEFT JOIN workspace_abuse_policies p ON p.workspace_id = w.id
WHERE p.workspace_id IS NULL;

CREATE TABLE workspace_host_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    host VARCHAR(255) NOT NULL,
    rule_type VARCHAR(32) NOT NULL,
    note VARCHAR(255) NULL,
    created_at TIMESTAMPTZ NOT NULL,
    created_by_owner_id BIGINT NOT NULL
);

CREATE UNIQUE INDEX uq_workspace_host_rules_host_type
    ON workspace_host_rules (workspace_id, lower(host), rule_type);
CREATE INDEX idx_workspace_host_rules_workspace_rule_type
    ON workspace_host_rules (workspace_id, rule_type);

CREATE TABLE workspace_abuse_host_stats (
    workspace_id BIGINT NOT NULL,
    host VARCHAR(255) NOT NULL,
    signal_count BIGINT NOT NULL,
    last_signaled_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (workspace_id, host)
);
