CREATE TABLE query_replica_runtime_state (
    replica_name VARCHAR(64) PRIMARY KEY,
    enabled BOOLEAN NOT NULL,
    last_heartbeat_at TIMESTAMPTZ NULL,
    last_replica_visible_event_at TIMESTAMPTZ NULL,
    last_fallback_at TIMESTAMPTZ NULL,
    last_fallback_reason VARCHAR(512) NULL,
    lag_seconds BIGINT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

INSERT INTO query_replica_runtime_state (
    replica_name,
    enabled,
    updated_at
) VALUES (
    'primary-query-replica',
    FALSE,
    now()
);

CREATE TABLE query_replica_fallback_log (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    replica_name VARCHAR(64) NOT NULL,
    fallback_reason VARCHAR(512) NOT NULL,
    request_path VARCHAR(255) NULL,
    workspace_id BIGINT NULL,
    triggered_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_query_replica_fallback_log_replica_triggered
    ON query_replica_fallback_log (replica_name, triggered_at DESC);

CREATE INDEX idx_query_replica_fallback_log_workspace_triggered
    ON query_replica_fallback_log (workspace_id, triggered_at DESC);
