CREATE TABLE workspace_recovery_drills (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    workspace_id BIGINT NOT NULL,
    requested_by_owner_id BIGINT NOT NULL,
    source_export_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    dry_run BOOLEAN NOT NULL,
    target_mode VARCHAR(32) NOT NULL,
    summary_json JSONB NULL,
    created_at TIMESTAMPTZ NOT NULL,
    started_at TIMESTAMPTZ NULL,
    completed_at TIMESTAMPTZ NULL,
    failed_at TIMESTAMPTZ NULL,
    last_error VARCHAR(1024) NULL,
    CONSTRAINT chk_workspace_recovery_drills_status
        CHECK (status IN ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED')),
    CONSTRAINT chk_workspace_recovery_drills_target_mode
        CHECK (target_mode IN ('SHADOW_VALIDATE', 'EMPTY_WORKSPACE_RESTORE', 'CONFLICT_ANALYSIS'))
);

CREATE INDEX idx_workspace_recovery_drills_workspace_created
    ON workspace_recovery_drills (workspace_id, created_at DESC);
