CREATE TABLE link_clicks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(64) NOT NULL,
    clicked_at TIMESTAMP WITH TIME ZONE NOT NULL,
    user_agent VARCHAR(1024),
    referrer VARCHAR(2048),
    remote_address VARCHAR(128),
    CONSTRAINT fk_link_clicks_slug FOREIGN KEY (slug) REFERENCES links (slug) ON DELETE CASCADE
);

CREATE INDEX idx_link_clicks_slug ON link_clicks (slug);
