CREATE TABLE privileged_action_approvals (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    workspace_id bigint NOT NULL,
    action_type varchar(64) NOT NULL,
    initiator_owner_id bigint NOT NULL,
    approver_owner_id bigint NOT NULL,
    status varchar(32) NOT NULL CHECK (status IN ('APPROVED', 'CONSUMED', 'EXPIRED')),
    created_at timestamptz NOT NULL,
    consumed_at timestamptz NULL,
    expires_at timestamptz NOT NULL
);

CREATE INDEX idx_privileged_action_approvals_lookup
    ON privileged_action_approvals (workspace_id, action_type, initiator_owner_id, status);

CREATE INDEX idx_privileged_action_approvals_expires_at
    ON privileged_action_approvals (expires_at);
